
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@0
  inputs:
    location: 'C:\Users\TejasGowdaS\Downloads\Katalon_Studio_Windows_64-7.9.1'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\TejasGowdaS\Katalon Studio\DevTest\DevTest.prj" -retry=0 -testSuitePath="Test Suites/Test Suite 1" -executionProfile="default" -browserType="Chrome" -apiKey="f61b66f5-069a-4c6e-ba68-c9b918d77571" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'