
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@0
  inputs:
    version: '7.1.1'
    executeArgs: 'katalonc -noSplash -runMode=console  -retry=0 -testSuitePath="Test Suites/Test Suite 1" -executionProfile="default" -browserType="Chrome" -apiKey="f61b66f5-069a-4c6e-ba68-c9b918d77571" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'